### ISSUE TITLE
Implement Pedigree Cohorts (Ascertain Pedigrees backend)

### ISSUE THREAD

**Issue by Viqsi** [MathematicalMedicine/diverweb-issues#135]
Have to be able to make the actual cohorts and all.

Possibly BLOCKED by #134, unless inspiration strikes. @WValenti is in a better position to comment on that. A copy of the spec document is also attached to that issue.

**Comment by WValenti** [comment]
Very good. I'm working on it today and tomorrow (after DMD, and the ISI meeting).

**Comment by WValenti** [comment]
Enlarging and rearranging a bit:
"Parameters passed would be: name, desc, project id, variable name, constraining value, pedigree count, pedigree count constraint, minimum number of individuals for which the constraint applies" becomes:

1. inUserName
2. inProjectId
3. inNewName - new pedigree cohort name, will be all family member ind_ids for families with at least the specified number of individuals of interest in the parent cohort
4. inNewDesc - description of new cohort
5. inParentCohort - defines starting set of individuals, because it probably isn't everyone!
6. inVariableOfInterest - variable used to identify individuals of interest in the parent cohort
7. inValueOfInterest - value of variable of interest used to tally up individuals of interest by family for possible inclusion in the new pedigree cohort
8. inInclusionThreshold - minimum number of individuals of interest needed to warrant inclusion of their family in the new pedigree cohort

How To:

1. Create or identify ALL_EXISTS cohort using inVariableOfInterest and return cohortId into valuesCohortId;
2. CREATE TEMPORARY TABLE ascertainment_candidates AS SELECT a.ind_id, a.value, b.fam_id FROM cohortInds a, dist_common b WHERE a.cohortId = valuesCohortId AND a.ind_id = b.ind_id;
3. CREATE TEMPORARY TABLE ascertained_fam_ids AS SELECT fam_id FROM ascertainment_candidates WHERE value = inValueOfInterest GROUP BY fam_id HAVING count(*) >= inInclusionThreshold;
4. Create an empty, properly named and described pedigree cohort with insertions into cohort tables;
5. INSERT INTO cohortInds (ind_id, value) SELECT DISTINCT ind_id, fam_id FROM dist_common WHERE fam_id IN (SELECT fam_id FROM ascertainment_fam_ids); -- this may vary depending upon if we want fam_id or inVariableOfInterest stored in value

**Comment by WValenti** [comment]
I lightly tested the above and it seems to work.  Please give feedback.

**Comment by WValenti** [comment]
REVISED HOW-TO after discussion with VV. "Family First" - the change is to get ALL family members for those individuals in the initial cohort and apply the constraint to them.

How To:

1. Create or identify the ALL_EXISTS cohort for inVariableOfInterest and return cohortId into valuesCohortId;
2. CREATE TEMPORARY TABLE ascertainment_candidates AS SELECT a.ind_id, a.value, b.fam_id FROM cohortInds a, dist_common b WHERE a.cohortId = valuesCohortId AND a.ind_id = b.ind_id AND b.fam_id IN (SELECT DISTINCT a.fam_id FROM dist_common a, cohortInds b WHERE b.cohortId = parentCohortId AND a.ind_id = b.ind_id); -- This is a cohort of ALL individuals with values for the variable of interest who are in families from the parent cohort.
3. CREATE TEMPORARY TABLE ascertained_fam_ids AS SELECT fam_id FROM ascertainment_candidates WHERE value = inValueOfInterest GROUP BY fam_id HAVING count(*) >= inInclusionThreshold;
4. Create an empty, properly named and described pedigree cohort with insertions into cohort tables;
5. INSERT INTO cohortInds (ind_id, value) SELECT DISTINCT ind_id, fam_id FROM dist_common WHERE fam_id IN (SELECT fam_id FROM ascertained_fam_ids); -- this may vary depending upon if we want fam_id or inVariableOfInterest stored in value. 

Test with cohortId 644 (MDD with AH_Yes - 148 ind_ids) as parentCohortId, cohortId 639 (I10920_ALL_EXISTS) as valuesCohortId, inValueOfInterest = 1, and inInclusionThreshold = 2.

**Comment by Viqsi** [comment]
Oh crud. I screwed up. ☹️

The parameters are subtly incorrect; I got them mixed up. The first few are the same: name, desc, project id, variable name, variable constraining value. What I mixed up was the pedigree counts - the "minimum number of individuals" is for PEDIGREE SIZE, not for whom the constraint applies. The remaining three are: minimum number of individuals in pedigree, constraint-applied count, constraint-applied count constraint. Which means, yeah, we have to have a "less than/greater than/equal to" control for the number of folks for whom inValueOfInterest applies.

I'm not sure of how to fix that with the queries you've got. Mea maxima culpa... ☹️

**Comment by Viqsi** [comment]
After further face-to-face conversation, apparently the queries above *don't* need fixing; just the frontend stuff I was working on. I screwed up but @WValenti nonetheless Did The Right Thing. Whew.

**Comment by WValenti** [comment]
So I pushed code that seems to work (on ada DIVER only for now):
```
CALL API_AscertainCohort('testuser', 16, 'testPC', 'Test of ped cohort', 644, 'i10920', '1', 2, @oNC); Select @oNC;
+---------------+-------------+
| new_cohort_id | cohort_rows |
+---------------+-------------+
|           669 |           0 |
+---------------+-------------+
1 row in set (0.16 sec)

Query OK, 449 rows affected (0.87 sec)

+------+
| @oNC |
+------+
|  669 |
+------+
1 row in set (0.03 sec)

```
...populates cohort-related tables:
```
Select * from cohorts where cohortId = 669;
+----------+----------+-----------+---------------------+--------+----------+--------+-----------+-----------+--------------------+---------------+--------------------+--------------->
| cohortId | owner    | projectId | creationDate        | name   | rowCount | parent | parentAId | parentBId | description        | variable_name | include_harmonized | constraint_typ>
+----------+----------+-----------+---------------------+--------+----------+--------+-----------+-----------+--------------------+---------------+--------------------+--------------->
|      669 | testuser |        16 | 2023-05-24 21:15:23 | testPC |        0 | NULL   |         1 |      NULL | Test of ped cohort | i10920_PC     | Y                  | EXISTS        >
+----------+----------+-----------+---------------------+--------+----------+--------+-----------+-----------+--------------------+---------------+--------------------+--------------->

```
...and pedigreeCohortInds:
```
Select count(*), fam_id, value from pedigreeCohortInds where cohortId = 669 group by fam_id, value;
+----------+------------+-------+
| count(*) | fam_id     | value |
+----------+------------+-------+
|        2 | 7-83-03070 | NULL  |
|        2 | 7-83-03070 | 1     |
|        5 | 7-83-03196 | NULL  |
|        1 | 7-83-03196 | 0     |
|        2 | 7-83-03196 | 1     |
|       10 | 7-83-03219 | NULL  |
|        2 | 7-83-03219 | 1     |
|        4 | 7-83-03222 | NULL  |
|        2 | 7-83-03222 | 1     |
|        3 | 7-84-04028 | NULL  |
|        2 | 7-84-04028 | 1     |
|        3 | 7-84-04085 | NULL  |
|        2 | 7-84-04085 | 1     |
|        3 | 7-85-05087 | NULL  |
|        2 | 7-85-05087 | 1     |
|        4 | 7-85-05095 | NULL  |
|        5 | 7-85-05095 | 0     |
|        3 | 7-85-05095 | 1     |
+----------+------------+-------+

```
