### ISSUE TITLE
Change searches from absolute strings to tokenized keywords

### ISSUE THREAD

**Issue by WValenti** [MathematicalMedicine/diverweb-issues#26]
["heard voices"] finds no matches, while [heard voices] does.

**Comment by Viqsi** [comment]
Searching is done via a SQL LIKE in diverRPC and the API (literally, `f"%{searchstring}%` in diverRPC.py), so I don't think any tokenization of keywords is happening in any case. So quotes would be kind of meaningless.

Of course, the fact that it *is* literal strings as is ("quotes are always on", after a fashion) and not tokenized keywords might itself be an issue, buuuuuut I'm not sure offhand how to implement that...

**Comment by Viqsi** [comment]
Per meeting discussion, yes we want tokenized keyword searches.

**Comment by Viqsi** [comment]
(Blocked by the HG Supervariables discussion because that involves significant changes to search)

**Comment by Viqsi** [comment]
Skype conversation just a minute or two ago:

Jo, 10:54 AM
https://dev.mysql.com/doc/refman/8.0/en/fulltext-boolean.html and https://mariadb.com/kb/en/full-text-index-overview/ <-- this looks like it might be a useful thing to do for our variable search setup
Bill, 10:54 AM
Yes, because our current search is currently really one word
And boolean is awesome.
Jo, 10:54 AM
yeah
the examples presume text records that haven't been normalized the way you did with question/explicit/implicit, so I'm not sure how that works, but I figure it's something you can work out. we'd also need to get construct variable descriptions in there too
but after that, so much shiny
