### ISSUE TITLE
Where is GT and LT...and we need to handle numeric comparison (e.g. "2" !> "15")

### ISSUE THREAD

**Issue by WValenti** [MathematicalMedicine/diverweb-issues#39]
Missing constraints in webapp, and we need to consider the difference between alpha and numeric ordering for comparison.

**Comment by Viqsi** [comment]
Those constraints are (AFAIK) not showing right now because every single variable is reported to the webapp as TEXT type, for which GT/LT doesn't apply. (Previously they were all getting reported as DATE type).

The actual solution is to have actual variable types reported for each variable. Which is, IIRC, a future milestone...

**Comment by Viqsi** [comment]
Marking as invalid and closing because this is not actually about a bug in the code; it's about not having particular metadata in the DB, and those issues are separate.
