### ISSUE TITLE
Empty (nothing found) searches show an error in the webapp

### ISSUE THREAD

**Issue by WValenti** [MathematicalMedicine/diverweb-issues#48]
Empty results from searches show an error in the webapp. This was a pain to find, as I ran into it while debugging REGEX searches, and MOST of them were always failing at the time.

**Comment by WValenti** [comment]
proccalls_errcheck was incorrectly raising an error (DBDeniedError which doesn't seem to do anything), but changing invocation from search function to include "empty_OK" as True fixes that (mostly). Handling empty results and whether it should be OK remains a problem across most interactions, and needs review and correction.

**Comment by Viqsi** [comment]
(Affected by the HG Supervariables question because that question involves significant changes to search)

**Comment by Viqsi** [comment]
Leaving this open because the error message is 1) inconsistent (I got different ones in searching for a variable to compare to another versus searching for a variable to build a cohort around), and 2) unclear and possibly unhelpful. But that's a polish issue, so this is also low priority as a result.

**Comment by Viqsi** [comment]
...simple enough that I just went ahead and got it out of the way anyways.
