### ISSUE TITLE
JSON description of construct variable in "Combine Two Variables" has bare keyword breaking parse

### ISSUE THREAD

**Issue by WValenti** [MathematicalMedicine/diverweb-issues#70]
(base) Huygens_/Volumes/MathMed/source/git/diverRPC_$ cat >AHxHearingImp_actual.JSON
{'construct_type': 'merge',
 'defaultValue': None,
 'description': 'Auditory hallucinations combined with hearing impairment',
 'name': 'AHxHearingImp',

Note the 'defaultValue': None, in which "None" is not quoted.  This causes a parse fail and I'm having to edit to get around it for the time being.

**Comment by WValenti** [comment]
Note that I am "patching" this bug in the SP:

diverRPC-procs.sql.pyexp:    SET fixedJSONdefinition = REPLACE(inJSONdefinition, ' None,', '"None",');

But it should be fixed in diverweb.

**Comment by Viqsi** [comment]
This is a little bit of a between-languages oddity. The JSON actually being sent has defaultValue as "null", which is JSONese for "no value". "None" is Pythonese for "no value". That suggests that what's going on is that the database is being passed Python dicts instead of JSON objects (and they're superficially similar enough in all other ways that nothing else was exploding).

That whole "passing Python dicts instead of JSON objects" bit was causing other problems elsewhere and so I thought it was already substantially fixed by just forcibly always converting from dict to JSON before sending to the SPs; I'll have to review and make sure that that's not falling through gaps. It could be that this bug has already been fixed but the fix was never noticed!

**Comment by Viqsi** [comment]
Fixed as part of MathematicalMedicine/diverRPC@74482d4.
