### ISSUE TITLE
Multiple-variable construct JSON loses first variable_name

### ISSUE THREAD

**Issue by WValenti** [MathematicalMedicine/diverweb-issues#72]
Created w/3 variables, JSON looks good EXCEPT first variable name is missing in all constraints (still in list of variables).

Create screenshot:
![Screen Shot 2022-11-12 at 12 46 35 PM](https://user-images.githubusercontent.com/3909236/201487777-26075315-8a44-4f7b-a8e8-224008b55d49.png)

JSON received by diverRPC screenshot:
![Screen Shot 2022-11-12 at 12 48 14 PM](https://user-images.githubusercontent.com/3909236/201487864-19440500-cfd8-4dee-9e7d-f620e4f2b771.png)

**Comment by Viqsi** [comment]
This appears to happen if the variable name never gets changed when picking constraints. Since it defaults to the first variable we have selected, the user doesn't see anything wrong, but setConstraintVariableName in MultiLineConstraint never actually gets informed of that default name.

**Comment by Viqsi** [comment]
I *think* this is happening because during rerenders in MultiLineConstraint, a local const "variable" (which is supposed to be that constraint group's constraining variable for all constraints) may be somehow getting out of sync with what the constraint group thinks is going on (things being tracked in two different places). HOW that's happening I do not know.

At first this comment was going to be "I do not know how what I did fixed it and I don't trust it, whimper whimper", but I think I now have *some* basis with which to work.

I feel like the lesson being learned here is "you can never shortcut anything or have scope-local copies of anything". Something something anti-Javascript rant here.
